#ifndef APPLICATION_API_DATASTRUCTURES_MULTITHREADING_SHAREDMUTEX_HPP_
#define APPLICATION_API_DATASTRUCTURES_MULTITHREADING_SHAREDMUTEX_HPP_

#include "boost/thread/shared_mutex.hpp"

namespace api {
using SharedMutex = boost::shared_mutex;
}

#endif  // APPLICATION_API_DATASTRUCTURES_MULTITHREADING_SHAREDMUTEX_HPP_
