#ifndef APPLICATION_API_DATASTRUCTURES_MULTITHREADING_THREADPOOL_HPP_
#define APPLICATION_API_DATASTRUCTURES_MULTITHREADING_THREADPOOL_HPP_

#define BOOST_THREAD_VERSION 5
#define BOOST_THREAD_USES_LOG
#define BOOST_THREAD_USES_LOG_THREAD_ID
#define BOOST_THREAD_QUEUE_DEPRECATE_OLD
#if !defined BOOST_NO_CXX11_DECLTYPE
#define BOOST_RESULT_OF_USE_DECLTYPE
#endif

// booost
#include "boost/thread/thread_pool.hpp"

namespace api {
using ThreadPool = boost::basic_thread_pool;
}

#endif //! APPLICATION_API_DATASTRUCTURES_MULTITHREADING_THREADPOOL_HPP_
