#ifndef APPLICATION_KERNEL_KERNELTASK_HPP_
#define APPLICATION_KERNEL_KERNELTASK_HPP_

namespace impl {
class KernelTask {};
}  // namespace impl
#endif APPLICATION_KERNEL_KERNELTASK_HPP_ // !APPLICATION_KERNEL_KERNELTASK_HPP_
